import type { Metadata } from 'next'

import { Providers } from 'src/lib/providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <Providers>{children}</Providers>
    </html>
  )
}
